// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzjgUzRntx3bX81JNTVJGKOitN33l6zpQ',
    appId: '1:878557644650:web:c393bcfa54b525c7f58713',
    messagingSenderId: '878557644650',
    projectId: 'app-test-ce8b0',
    authDomain: 'app-test-ce8b0.firebaseapp.com',
    storageBucket: 'app-test-ce8b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWiB0hW_T3M7RahYFAVACxynG2O4JMmR8',
    appId: '1:878557644650:android:ad163ee16df4170ef58713',
    messagingSenderId: '878557644650',
    projectId: 'app-test-ce8b0',
    storageBucket: 'app-test-ce8b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZECQFl5wjQb-rTXaNJcdA5DW_uGDjNhI',
    appId: '1:878557644650:ios:4d1a5a0852d3a092f58713',
    messagingSenderId: '878557644650',
    projectId: 'app-test-ce8b0',
    storageBucket: 'app-test-ce8b0.appspot.com',
    androidClientId: '878557644650-o5lsilppoi007lfa41na297fa3rs3je4.apps.googleusercontent.com',
    iosClientId: '878557644650-r7rr12vb5php06kj9ih01rjj92cck1ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZECQFl5wjQb-rTXaNJcdA5DW_uGDjNhI',
    appId: '1:878557644650:ios:4d1a5a0852d3a092f58713',
    messagingSenderId: '878557644650',
    projectId: 'app-test-ce8b0',
    storageBucket: 'app-test-ce8b0.appspot.com',
    androidClientId: '878557644650-o5lsilppoi007lfa41na297fa3rs3je4.apps.googleusercontent.com',
    iosClientId: '878557644650-r7rr12vb5php06kj9ih01rjj92cck1ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTest',
  );
}
